name: 'PR QA Comments Helper 2'
description: 'A GitHub Action to help with PR QA Comments and run actions on PRs'
inputs:
  repo-owner: 
    description: 'The owner of the repo to run the action on'
    required: true
  repo-name:
    description: 'The name of the repo to run the action on'
    required: true
  pr-number:
    description: 'The PR number to run the action on'
    required: true
  github-token:
    description: 'GitHub access token (required for adding labels)'
    default: '${{ secrets.GITHUB_TOKEN }}'
  label-pass:
    description: 'The label to add to the PR if the QA check passes (optional)'
  label-fail:
    description: 'The label to add to the PR if the QA check fails (optional)'
  ready-for-review-label:
    description: 'The label to add to the PR if the QA check passes (optional)'
runs:
  using: 'node16'
  main: 'dist/index.mjs'
