on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment (for QA)
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: PR QA Comments Helper
        uses: auroraisluna/zxvczVcvasfdadsf@tt9
        with:
          repo-owner: ${{ github.event.repository.owner.login }}
          repo-name: ${{ github.event.repository.name }}
          pr-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.PAT }}
          label-pass: 'QA Passed'
          label-fail: 'QA Failed'
          label-rtt: 'QA Ready to Test'